export const CART = {
  GET_CART: "GET_CART",
  GET_CART_LENGTH: "GET_CART_LENGTH",
};

export const FAV = {
  GET_FAV: "GET_FAV",
  GET_FAV_LENGTH: "GET_FAV_LENGTH",
};

export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
};
